apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgres.persistence.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/{{ .Release.Name }}/postgres"
