apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
stringData:
    POSTGRES_USER: "{{ .Values.postgres.username }}"
    POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
    POSTGRES_DB: "{{ .Values.postgres.database }}"